name: Tagbot
on: [pull_request]

permissions:
  pull-requests: write

jobs:
  tagbot:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Get packages
      run: pip install gitpython requests

    - name: Tag and comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/workflows/tagbot.py

