name: Tagbot
on: [pull_request_target]

jobs:
  tagbot:
    if: github.event.pull_request.merge_commit_sha
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
    - name: Checkout base branch for workflow scripts
      uses: actions/checkout@v4

    - name: Checkout PR for computing diff
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.pull_request.merge_commit_sha }}"
        path: 'pr'
        fetch-depth: 0

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Get packages
      run: pip install gitpython requests

    - name: Tag and comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/workflows/tagbot.py

