name: Tagbot
on: [pull_request_target]

jobs:
  tagbot:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: |
        # Make sure the script is unmodified as it runs with write permissions
        echo "f525f362a99f13764791185da4d45959a632ef54e3b6b865461dabddb1b1df34 .github/workflows/tagbot.py"|sha256sum --check --status

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Get packages
      run: pip install gitpython requests

    - name: Tag and comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/workflows/tagbot.py

